# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - develop

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  - script: |
      npm run test-ci
    displayName: "npm test-ci"
  
  - task: PublishTestResults@2
    displayName: 'report on test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: './junit.xml'

  # - task: CopyFiles@2
  #   inputs:
  #     Contents: |
  #       .next/**
  #       public/**
  #       package.json
  #     TargetFolder: "$(Build.ArtifactStagingDirectory)"
  #     CleanTargetFolder: true
  #     OverWrite: true

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '.'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "app"
      publishLocation: "Container"